# 
# instructions to build the mkr_django Docker image
#
FROM ubuntu:14.04
MAINTAINER Kristian Rother <krother@academis.eu>
RUN echo "Hello world!"
RUN apt-get install -y git
RUN git clone https://github.com/lenarother/mkr.git
